scope:                                    basic
key:
  name:                                   name
fields:
  ip:                                     ip
  servername:                             server.name
  servicetype:                            (HTTP|FTP|TCP|UDP|SSL|SSL_BRIDGE|SSL_TCP|DTLS|NNTP|RPCSVR|DNS|ADNS|SNMP|RTSP|DHCPRA|ANY|SIP_UDP|SIP_TCP|SIP_SSL|DNS_TCP|ADNS_TCP|MYSQL|MSSQL|ORACLE|RADIUS|RADIUSListener|RDP|DIAMETER|SSL_DIAMETER|TFTP|SMPP|PPTP|GRE|SYSLOGTCP|SYSLOGUDP|FIX|SSL_FIX|USER_TCP|USER_SSL_TCP)
  port:                                   int
  cleartextport:                          int
  cachetype:                              (TRANSPARENT|REVERSE|FORWARD)
  maxclient:                              double
  healthmonitor:                          (YES|NO)
  maxreq:                                 double
  cacheable:                              (YES|NO)
  cip:                                    (ENABLED|DISABLED)
  cipheader:                              string
  usip:                                   (YES|NO)
  pathmonitor:                            (YES|NO)
  pathmonitorindv:                        (YES|NO)
  useproxyport:                           (YES|NO)
  sc:                                     (ON|OFF)
  sp:                                     (ON|OFF)
  rtspsessionidremap:                     (ON|OFF)
  clttimeout:                             int
  svrtimeout:                             int
  customserverid:                         string
  serverid:                               double
  cka:                                    (YES|NO)
  tcpb:                                   (YES|NO)
  cmp:                                    (YES|NO)
  maxbandwidth:                           double
  accessdown:                             (YES|NO)
  monthreshold:                           double
  downstateflush:                         (ENABLED|DISABLED)
  tcpprofilename:                         nstcpprofile.name
  httpprofilename:                        nshttpprofile.name
  hashid:                                 double
  comment:                                string
  appflowlog:                             (ENABLED|DISABLED)
  netprofile:                             string
  td:                                     double
  processlocal:                           (ENABLED|DISABLED)
  dnsprofilename:                         dnsprofile.dnsprofilename
  monconnectionclose:                     (RESET|FIN)
update:
  - maxclient
  - maxreq
  - cacheable
  - cip
  - cipheader
  - usip
  - pathmonitor
  - pathmonitorindv
  - useproxyport
  - sc
  - sp
  - rtspsessionidremap
  - healthmonitor
  - clttimeout
  - svrtimeout
  - customserverid
  - serverid
  - cka
  - tcpb
  - cmp
  - maxbandwidth
  - accessdown
  - monthreshold
  - downstateflush
  - tcpprofilename
  - httpprofilename
  - hashid
  - comment
  - appflowlog
  - netprofile
  - processlocal
  - dnsprofilename
  - monconnectionclose
